version: '3.8'

services:

  # ─── API NestJS ───────────────────────────────────────────
  api:
    image: ${DOCKER_USERNAME}/alquileres-api:latest
    container_name: alquileres-api
    restart: unless-stopped
    env_file:
      - .env
    expose:
      - "3000"  # Protegido del exterior. Nginx hablará con NestJS de manera interna.
    volumes:
      - vol-uploads:/app/uploads
    networks:
      - red-alquileres

  # ─── Frontend React (Nginx interno) ───────────────────────
  frontend:
    image: ${DOCKER_USERNAME}/alquileres-frontend:latest
    container_name: alquileres-frontend
    restart: unless-stopped
    expose:
      - "80"   # Nginx proxy lo consumirá internamente por este puerto.
    depends_on:
      - api
    networks:
      - red-alquileres

  # ─── Proxy Inverso Nginx Cifrado ──────────────────────────
  nginx:
    image: nginx:alpine
    container_name: alquileres-proxy
    restart: unless-stopped
    ports:
      - "80:80"     # Abre el puerto HTTP estándar al mundo para redirección
      - "443:443"   # Abre el puerto HTTPS cifrado y seguro al mundo
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro  # Mapea tus certificados de la EC2
    depends_on:
      - frontend
      - api
    networks:
      - red-alquileres

# ─── Volúmenes Estáticos ──────────────────────────────────────
volumes:
  vol-uploads:
    name: vol-uploads

# ─── Red Interna Privada ──────────────────────────────────────
networks:
  red-alquileres:
    name: red-alquileres